//! Generate docs/WORDS.md from word metadata (backlog item 22).
//!
//! Run: `cargo run --example generate_docs`
//!
//! The rs analog of forthic-ts's scripts/generate-docs.ts: word docs live
//! on the words themselves (register_words! documented form) and this
//! renders them. Undocumented words are listed explicitly so gaps stay
//! visible instead of silently missing.

use forthic::module::Module;
use forthic::modules::standard::{
    ArrayModule, BooleanModule, CoreModule, DateTimeModule, JSONModule, MathModule, RecordModule,
    StringModule,
};

fn main() {
    let modules: Vec<(&str, Module)> = vec![
        ("core", CoreModule::new().module().clone()),
        ("array", ArrayModule::new().module().clone()),
        ("boolean", BooleanModule::new().module().clone()),
        ("datetime", DateTimeModule::new().module().clone()),
        ("json", JSONModule::new().module().clone()),
        ("math", MathModule::new().module().clone()),
        ("record", RecordModule::new().module().clone()),
        ("string", StringModule::new().module().clone()),
    ];

    let mut out = String::from(
        "# Forthic Words (rust runtime)\n\n\
         Generated by `cargo run --example generate_docs` from word metadata — \
         do not edit by hand.\n",
    );
    let mut documented = 0;
    let mut undocumented_total = 0;

    for (name, module) in &modules {
        out.push_str(&format!("\n## {name}\n\n"));
        for (word, doc) in module.word_docs() {
            out.push_str(&format!(
                "- **{word}** `{}` — {}\n",
                doc.stack_effect, doc.description
            ));
            documented += 1;
        }
        let undocumented: Vec<String> = module
            .exportable_words()
            .iter()
            .filter(|w| w.doc().is_none())
            .map(|w| w.name().to_string())
            .collect();
        if !undocumented.is_empty() {
            undocumented_total += undocumented.len();
            out.push_str(&format!("\nUndocumented: {}\n", undocumented.join(", ")));
        }
    }

    std::fs::create_dir_all("docs").expect("create docs dir");
    std::fs::write("docs/WORDS.md", out).expect("write docs/WORDS.md");
    println!("Wrote docs/WORDS.md ({documented} documented, {undocumented_total} undocumented)");
}
